# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  cmp-dap = {
    pname = "cmp-dap";
    version = "d16f14a210cd28988b97ca8339d504533b7e09a4";
    src = fetchFromGitHub ({
      owner = "rcarriga";
      repo = "cmp-dap";
      rev = "d16f14a210cd28988b97ca8339d504533b7e09a4";
      fetchSubmodules = false;
      sha256 = "sha256-w+gGaZxXjb2B0dMXhfduEQKtO5CmQnuUdh4otpcsFuc=";
    });
  };
  cmp-nixpkgs = {
    pname = "cmp-nixpkgs";
    version = "12bebfe528ecabf65ddab5d50521487cc413ebca";
    src = fetchFromGitHub ({
      owner = "gravndal";
      repo = "cmp-nixpkgs";
      rev = "12bebfe528ecabf65ddab5d50521487cc413ebca";
      fetchSubmodules = false;
      sha256 = "sha256-kRdXFhcrAzWFK3CVt5BoQKO2HkGH2ujmtNOFX6uo9jQ=";
    });
  };
  cmp-path = {
    pname = "cmp-path";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  neozoom-nvim = {
    pname = "neozoom-nvim";
    version = "ba9471fddd56d0a5bea24c9efcc18866f49d2996";
    src = fetchFromGitHub ({
      owner = "nyngwang";
      repo = "NeoZoom.lua";
      rev = "ba9471fddd56d0a5bea24c9efcc18866f49d2996";
      fetchSubmodules = false;
      sha256 = "sha256-f2wGv9HlZMD3JmWez/6KrNqTrAvgqUC8MKq/xrgFBug=";
    });
  };
  obsidian-nvim = {
    pname = "obsidian-nvim";
    version = "06c1d134b9bbfa40ed1285cbda1c24b0a09e59d8";
    src = fetchFromGitHub ({
      owner = "epwalsh";
      repo = "obsidian.nvim";
      rev = "06c1d134b9bbfa40ed1285cbda1c24b0a09e59d8";
      fetchSubmodules = false;
      sha256 = "sha256-gm3ftKRfEYpBz+1o3M1Y1NPGrWNacb7WbyrfMJuJtfU=";
    });
  };
}
